### ISSUE TITLE
[pt-BR] Aprimorar documentação

### ISSUE THREAD

**Issue by serradura** [serradura/u-case#65]
https://github.com/serradura/u-case/blob/main/README.pt-BR.md

# 3.0.0

## Atualizar README.pt-BR.md
- [ ] Adicionar uma boa introdução (Getting started).
- [ ] Adicionar algumas recomendações de uso (approach: make it work, right and fast).

### Adicionar exemplos sobre os recursos: 
- [ ] `Micro::Case.then` e `Micro::Cases::Flow#then` e do `Micro::Case::Result#then` recebendo um flow. #63.
  A composição está a um passo de qualquer ponto. By @josuetex

<br/>

- [ ] Casos de uso com etapas internas usando seus métodos privados. Com **lambdas** #56 e **methods**  #61
  - [ ] Adicionar exemplos que fazem uso de keywords args quando o `then`ou `|` recebem uma instância de method. #68, #69
  - [ ] Adicionar mais testes para este recurso + combinado com outros. Exemplo: flow, safe_flow, inner flow, outros tipos de casos/fluxos usando um caso com etapas internas em suas etapas.

---

## Outros docs

- [ ] Adicionar um guia de migração da versão 2 para a versão 3.
- [ ] Adicionar um Changelog (https://github.com/serradura/u-case/issues?q=is%3Aclosed+is%3Aissue+milestone%3A3.0.0+)

# 3.1.0
- [ ] Atualizar o README com as adições #77, #72
- [ ] Atualizar o Changelog com as adições #77, #72

# 4.0.0
- [ ] Atualizar o README com as adições #29
- [ ] Atualizar o Changelog com as adições #29

# 4.1.0
https://github.com/serradura/u-case/pulls?q=is%3Aclosed+is%3Apr+milestone%3A4.1.0
- [ ] Atualizar o README com as adições
- [ ] Atualizar o Changelog com as adições

# 4.2.0

- [ ](README + Changelog) https://github.com/serradura/u-case/milestone/9

# Recomendação para colaboradores

Usem `Update pt-BR docs` nas mensagens de commit. 😉

**Comment by mrbongiolo** [comment]
Ao criar um case com `Micro::Case` e definindo `attributes :a, :b`, o case aceita normalmente uma chamada como `MyCase.call('1', 2)`.

Nesse caso ao tentar acessar os atributos `a` e `b` dentro do case, os mesmos vão retornar `nil`. Pelo que vi na documentação o `Micro::Case::Strict` pode ser utilizado para jogar um erro caso os atributos utilizados no `call` não estejam batendo com os definidos.

Pode ser interessante utilizar o `Micro::Case::Strict` como exemplo inicial na documentação ou deixar mais claro que ele pode ser utilizado nesses casos, já que para quem está começando pode não ficar muito claro pq os atributos estão vazios.
